config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'root#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  root to: 'books#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
  		redirect_to book_path(@book)
  		flash[:notice] = "Book was successfully created."
  	else
      @books = Book.all
      render action: :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "Book was successfully updated."
    else
      render action: :edit
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <label>Title</label>
  <br><%= f.text_field :title %></br>
  <br>
  <label>Body</label>
  <br><%= f.text_area :body %></br>
  <br><%= f.submit "Update Book" %></br>
<% end %>

 <br>
 <%= link_to "Show", book_path %>
 |
 <a href="/books">Back</a>

app/views/books/index.html.erb
<header>
	<h1>Books</h1>
</header>


<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td>
				<%= link_to "show", book_path(book.id) %>
				<%= link_to "edit", edit_book_path(book.id) %>
				<%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<h2>New book</h2>
<%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
	<label>Title</label>
	<br><%= f.text_field :title %></br>
	<br>
    <label>Body</label>
	<br><%= f.text_area :body %></br>
	<br><%= f.submit "Create Book" %></br>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="flash">
<% flash.each do |key, value| %>
	<%= content_tag(:div, value, class: "#{key}") %>
<% end %>
</div>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
 <strong>Body:</strong>
 <%= @book.body %>
</p>

 <%= link_to "Edit", edit_book_path(@book.id) %>
 |
 <a href="/books">Back</a>

app/views/books/top.html.erb
<body>
	<header>
		<h1>
			ようこそ <strong>Bookers</strong> へ！
		</h1>
	</header>

	<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
	</p>
	<p>印象を共有し交換することができます</p>
	<p>
		<%= link_to 'start', '/books' %>
	</p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>